version: 2

sources:
    - name: TPCH_SF1
      schema: raw_tpch
      tables:
        - name: partsupp
        - name: nation
        - name: region
        - name: orders
        - name: lineitem
        - name: customer
        - name: part
        - name: supplier